# -*- coding: utf-8 -*-
"""Copy of Untitled124.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJXIo-jQACEmyhUlSWTKdnuZF6vRwUIe
"""



"""# 🧠 Building a Production-Grade Multi-Agent AI System
## *From first principles — using LangGraph, GROQ, and FAISS*

---

> **The Scene:**  It's 11:47 PM. Someone just ordered a pair of headphones online.
> Forty-five minutes later, they open the app and type:
>
> *"WHERE IS MY ORDER??? I need it by tomorrow morning 😤"*
>
> Behind that single panicked message, a real system needs to — **in under 2 seconds**:
>
> 1. 🧠 **Understand intent** — is this about tracking? A refund? Something else?
> 2. 🗄️ **Query the right database** — not all of them, just the right one
> 3. 💬 **Remember context** — did they mention their name 3 messages ago?
> 4. ✍️ **Respond like a human** — empathetic, accurate, fast
>
> **By the end of this session, you will have built exactly that system.**
> And you'll understand every single line of it.

---

### What we're building

A **multi-agent customer service bot** with:

| Capability | What it means |
|------------|---------------|
| 🤖 Specialized Agents | Different AI specialists for different query types |
| 🧠 LLM-powered Routing | The system reads and *reasons* about where to send each query |
| 🗄️ Real database lookups | Live SQL queries, not hardcoded answers |
| 🔍 Semantic FAQ search | Understands meaning, not just keywords |
| 💾 Conversation memory | Remembers what was said earlier in the same session |
| 📊 Visual architecture | You can draw and inspect the entire system as a graph |

### Tech stack

| Tool | What it does |
|------|-------------|
| **LangGraph** | Framework for building stateful, visual AI agent systems |
| **GROQ + Llama 3.3** | Free, fast LLM inference |
| **HuggingFace Embeddings** | Free semantic text embeddings (no API key needed) |
| **FAISS** | Facebook's vector similarity search library |
| **SQLAlchemy + SQLite** | Database ORM — query with Python, not raw SQL |
| **Gradio** | Instant chat UI in one function call |

---
## The Mental Model Before We Write Any Code 🍱

### Mumbai's Dabbawala Network

Every day, Mumbai's Dabbawala network delivers **200,000+ home-cooked lunchboxes** across the city — with a documented error rate of **1 in 6 million deliveries**.

No computers. No GPS. Pure human coordination built on one idea:

> **"Don't let the same person both cook and deliver. Specialise."**

The sorting hub at Churchgate station doesn't cook anything. It just reads the box's destination code and routes it to the right carrier.

That's the entire architecture of what we're building today.

| Dabbawala System | Our AI System |
|-----------------|---------------|
| Sorting hub (reads codes, routes boxes) | **Supervisor Agent** (reads queries, routes to specialists) |
| Carrier A — North Mumbai route | **FAQ Agent** (handles policy questions) |
| Carrier B — South Mumbai route | **Order Agent** (handles tracking & delivery) |
| Carrier C — Corporate VIP route | **Recommendation Agent** (handles personalised suggestions) |
| The lunchbox (travels the whole route) | **LangGraph State** (carries messages through the system) |
| Delivery receipt log | **MemorySaver** (conversation history, never lost) |
| The full route map | **Graph visualisation** (we'll actually draw this!) |

**The key insight:** The sorting hub doesn't need to know what's inside the box.
It just needs to read the destination and route correctly.

Our Supervisor works the same way — it doesn't answer the customer's question.
It reads it, reasons about the intent, and hands it to the right specialist.

```
Customer Message
       ↓
  [Supervisor]  ← LLM reads intent, decides the route
       ↓
┌──────┬──────┬──────┐
│ FAQ  │ORDER │ REC  │  ← Specialists (each with their own tools & expertise)
└──────┴──────┴──────┘
       ↓
  Final Response
```

*(We'll turn this ASCII diagram into a live, interactive graph in Part 4)*

---
## Concept 1: What Is an AI Agent? 🤖

An **AI Agent** is not just an LLM that answers questions.

A plain LLM is like a very knowledgeable person locked in a room with no phone, no computer, and no way to look anything up. It can only work with what it already knows.

An **Agent** is that same person — but now they have **tools**: a phone, a computer, access to databases, the ability to take actions.

### The 3 ingredients of an agent

```
Agent = LLM (the brain)
      + Tools (the hands)
      + A loop (the persistence to keep going until the job is done)
```

### What is a Tool?

A Tool is a Python function that the LLM can **choose to call** when it needs to.

You tell the LLM: *"Hey, you have these tools available. Use them if you need to."*
The LLM decides: *"The user asked about order status. I should call the `lookup_order` tool."*

```python
# Example: you give the LLM this tool
@tool
def lookup_order(customer_name: str) -> str:
    '''Look up order details for a customer by name.'''
    # queries the actual database
    ...
```

### The ReAct Loop — how agents "think"

Agents follow a cycle called **ReAct** (Reason → Act → Observe → Repeat):

```
User: "What's the status of Bob Smith's order?"
                    ↓
LLM Thinks:   "I need to look up Bob's order. I'll call lookup_order."
                    ↓
LLM Acts:     lookup_order("Bob Smith")  ← calls the tool
                    ↓
LLM Observes: "Order #2: Wireless Mouse — Shipped on 12 Dec"
                    ↓
LLM Thinks:   "I have the answer. No more tools needed."
                    ↓
LLM Responds: "Hi! Bob's Wireless Mouse was shipped on 12 Dec and is on its way!"
```

The agent **loops** between thinking, acting, and observing until it's satisfied it has a complete answer. This is what separates an agent from a simple LLM call.

---
## Concept 2: What Is LangGraph — and Why Do We Need It? 🗺️

### The problem with building agents from scratch

You *could* build an agent using raw Python:
- Write the ReAct loop yourself
- Manage the tool dispatch yourself
- Handle errors yourself
- Build memory yourself

This works. But it's fragile, hard to debug, and impossible to visualise.

### LangGraph: agents as flowcharts

**LangGraph** lets you define your agent as a **graph**:
- **Nodes** = Python functions (each one does a specific job)
- **Edges** = connections between nodes (the flow of execution)
- **State** = the data that travels through the graph (shared memory)

Think of it like the **Delhi Metro map**:
- Each station (node) does one thing: board, travel, change lines
- The map (graph) shows all possible routes
- Your Oyster card (state) carries your journey data from station to station
- The route you take depends on conditional logic: "if destination is Noida, take Blue Line"

```
User Input
    ↓
[agent node]  ← LLM decides: do I need a tool?
    ↓ YES
[tools node]  ← Calls the tool, gets result
    ↓
[agent node]  ← LLM looks at result, decides: am I done?
    ↓ YES
 __end__
```

### The 5-Step LangGraph Recipe

*Every graph you will ever build in LangGraph follows exactly these 5 steps:*

| Step | What you do |
|------|-------------|
| **1. State** | Define what information travels through the graph |
| **2. Builder** | Create a `StateGraph` container |
| **3. Nodes** | Write Python functions that do the work |
| **4. Edges** | Connect the nodes (define the flow) |
| **5. Compile** | Lock it in and run it |

We will use this recipe for every agent and every graph in this notebook.
"""

# To run this code locally, ensure you install the required packages:
# pip install langchain langchain-groq langchain-community langchain-core langgraph langchain-huggingface sentence-transformers sqlalchemy faiss-cpu gradio

print("✅ All packages installed!")

"""---
## Setup: Install and Import Everything 📦

"""

import os, getpass, uuid
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

from typing import Annotated, Literal
from typing_extensions import TypedDict
from pydantic import BaseModel, Field
try:
    from IPython.display import Image, display
except ImportError:
    def Image(*args, **kwargs):
        return None
    def display(*args, **kwargs):
        raise RuntimeError("IPython display is not available in this environment.")


# LangChain
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from langchain_core.tools import tool

# LangGraph
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import create_react_agent
from langgraph.checkpoint.memory import MemorySaver

# Database
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime
from sqlalchemy.orm import declarative_base, sessionmaker
from datetime import datetime

import gradio as gr

print("✅ All imports successful!")

if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass.getpass("Enter your Groq API Key: ")

# timeout + max_retries keep a single hung/rate-limited call from blocking forever.
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0,
    timeout=30,        # abort any single call that stalls past 30s
    max_retries=2,     # retry transient errors twice, then fail fast (don't hang)
)
print("✅ LLM ready — llama-3.3-70b-versatile via Groq (free)")

"""---
## Part 1: The Data Layer — What Our Agents Will Work With

Our system needs two data sources:

1. **A relational database** (SQLite via SQLAlchemy) — stores customer orders
2. **A vector database** (FAISS) — stores FAQ documents for semantic search

### Why two different databases?

They solve different problems:

| Relational DB (SQLite) | Vector DB (FAISS) |
|------------------------|-------------------|
| "Find all orders for Bob Smith" | "Find FAQs about damaged items" |
| Exact matches, structured queries | Semantic similarity, meaning-based |
| Great for: orders, users, products | Great for: documents, FAQs, knowledge bases |
| Query with SQL / ORM | Query with natural language |

### What is an ORM?

**ORM = Object-Relational Mapper**. It lets you query a database using Python objects instead of writing raw SQL.

```python
# Raw SQL (traditional):
SELECT * FROM orders WHERE customer_name LIKE '%Bob%'

# ORM syntax (SQLAlchemy):
session.query(Order).filter(Order.customer_name.ilike("%Bob%")).all()
```

Same result. The ORM translates Python into SQL behind the scenes.
This is what libraries like SQLAlchemy and Django ORM do.

"""

# ─── ORDER DATABASE ───────────────────────────────────────────────────────────
Base = declarative_base()

class Order(Base):
    __tablename__ = 'orders'
    id            = Column(Integer,     primary_key=True)
    customer_name = Column(String(100), nullable=False)
    product       = Column(String(200), nullable=False)
    status        = Column(String(50),  nullable=False)
    price         = Column(Float,       nullable=False)
    order_date    = Column(DateTime,    default=datetime.utcnow)

# Create the database and table
engine = create_engine('sqlite:///shopbot.db', echo=False)
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()

# Populate with sample data
sample_orders = [
    Order(customer_name="Alice Johnson",  product="Laptop Pro 15",               status="Delivered",  price=1299.99),
    Order(customer_name="Bob Smith",      product="Wireless Mouse",              status="Shipped",    price=29.99),
    Order(customer_name="Alice Johnson",  product="USB-C Hub",                   status="Processing", price=49.99),
    Order(customer_name="Charlie Brown",  product="Mechanical Keyboard",         status="Delivered",  price=159.99),
    Order(customer_name="Diana Prince",   product="Monitor 27 inch",             status="Shipped",    price=399.99),
    Order(customer_name="Bob Smith",      product="Laptop Stand",                status="Delivered",  price=79.99),
    Order(customer_name="Rohan Sharma",   product="Webcam HD",                   status="Processing", price=89.99),
    Order(customer_name="Priya Patel",    product="Noise Cancelling Headphones", status="Shipped",    price=249.99),
]

session.query(Order).delete()
session.add_all(sample_orders)
session.commit()

customers = sorted({o.customer_name for o in sample_orders})
print(f"✅ Database ready — {len(sample_orders)} orders across {len(customers)} customers")
print(f"   Customers: {customers}")

"""### What is Semantic Search?

Traditional databases use **exact matching**: searching for "broken item" won't find a document that says "damaged product".

**Semantic search** converts text into numerical vectors called **embeddings** that capture *meaning*.
Similar meanings end up close together in vector space — even if the words are different.

```
"broken item"      → [0.23, 0.71, -0.14, ...]
"damaged product"  → [0.25, 0.69, -0.12, ...]   ← similar vector! close match ✅
"shipping time"    → [0.81, 0.02,  0.55, ...]   ← different meaning, far away ❌
```

**FAISS** (Facebook AI Similarity Search) stores these vectors and finds the closest matches instantly — even across millions of documents.

This is what powers Google Search, ChatGPT's memory, and every modern RAG system.

"""

# ─── FAISS KNOWLEDGE BASE ─────────────────────────────────────────────────────
faq_data = [
    "Return Policy: Return any item within 30 days of purchase for a full refund. Item must be in original condition with all packaging intact.",
    "Shipping Time: Standard shipping takes 5-7 business days. Express shipping takes 2-3 business days. Free shipping on orders over ₹999.",
    "International Shipping: We ship to over 100 countries. International orders typically take 10-15 business days.",
    "Order Tracking: Once your order ships, you'll receive a tracking number via email. Track in real-time on our website or app.",
    "Payment Methods: We accept Visa, Mastercard, UPI (PhonePe, GPay, Paytm), net banking, and zero-cost EMI options.",
    "Order Cancellation: Cancel within 24 hours of placing the order. After that, the order may already be dispatched.",
    "Damaged Items: Received a damaged item? Contact us within 48 hours with photos. We'll send a replacement or issue a full refund — no questions asked.",
    "Warranty: All electronics come with 1-year manufacturer warranty. Extended warranty available at checkout.",
    "Customer Support: Email support@shopbot.in | Call 1800-SHOPBOT (toll-free, 24/7) | Live chat on the website.",
    "Student Discount: Students get 15% off with a valid college/university ID. Verify your status at checkout.",
    "EMI Options: Zero-cost EMI available on orders above ₹3,000 with all major banks. Select EMI at checkout.",
    "GST Invoice: GST invoice is auto-generated for every order. Download anytime from your order history page.",
]

documents = [Document(page_content=faq) for faq in faq_data]

print("Building FAISS index... (downloads ~80MB embedding model on first run)")
embeddings  = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
vectorstore = FAISS.from_documents(documents, embeddings)
print(f"✅ Vector store ready — {len(faq_data)} FAQs indexed for semantic search")

# ─── See semantic search in action ───────────────────────────────────────────
test_queries = [
    "what if my package arrives broken",
    "can students get a discount",
    "how long does delivery take",
]

print("Semantic search demonstration:\n")
for q in test_queries:
    result = vectorstore.similarity_search(q, k=2)
    print(result)
    print(f"  Query:  '{q}'")
    print(f"  Match:  {result[0].page_content[:75]}...")
    print()

help(vectorstore.similarity_search)

"""---
## Part 2: Defining Tools — The `@tool` Decorator 🛠️

### What makes a good tool?

When you give a tool to an LLM, the LLM never sees your Python source code.
It only sees three things:

1. **The name** — `lookup_order`
2. **The description** — from the docstring
3. **The input schema** — from the type hints

The LLM uses the description to decide *when* to call the tool, and the type hints to decide *what to pass in*.

This means a well-written docstring is as important as the function itself.

```python
@tool
def lookup_order(customer_name: str) -> str:
    # ↑ type hint tells the LLM: pass a string here
    '''
    Look up order status for a customer by their name.
    Use when a customer asks about their order, tracking, or delivery status.
    # ↑ this docstring IS the tool's description. The LLM reads this.
    '''
    ...
```

### The `@tool` decorator

The `@tool` decorator from LangChain does three things automatically:
1. Wraps your function so the LLM can call it
2. Extracts the docstring as the tool description
3. Extracts the type hints as the input schema

No manual JSON schemas. No wrapper objects. Just a decorator.
"
"""

@tool
def search_faq(query: str) -> str:
    """
    Search the FAQ knowledge base for answers to customer questions.
    Use for questions about: return policy, shipping time, payment methods,
    order cancellation, warranty, student discounts, EMI options,
    GST invoices, and how to contact customer support.
    """
    results = vectorstore.similarity_search(query, k=2)
    if not results:
        return "No relevant information found in our FAQ."
    return "FAQ Results:\n\n" + "\n\n---\n\n".join(doc.page_content for doc in results)


@tool
def lookup_order(customer_name: str) -> str:
    """
    Look up order status and details for a customer by their name.
    Use when a customer asks about their order, wants tracking info,
    or asks about delivery status.
    Input: the customer's name (first name, last name, or full name).
    """
    if not customer_name or not customer_name.strip():
        return "I'd be happy to check! What name was the order placed under?"
    orders = session.query(Order).filter(
        Order.customer_name.ilike(f"%{customer_name}%")
    ).all()
    if not orders:
        return f"No orders found for '{customer_name}'. Please verify the name."
    result = f"Found {len(orders)} order(s) for {customer_name}:\n\n"
    for o in orders:
        result += (f"• Order #{o.id}: {o.product}\n"
                   f"  Status: {o.status} | Price: ₹{o.price:,.2f} | "
                   f"Date: {o.order_date.strftime('%d %b %Y')}\n\n")
    return result.strip()




@tool
def recommend_products(customer_name: str) -> str:
    """
    Recommend products to a customer based on their purchase history.
    Use when a customer asks for product suggestions, gift ideas,
    or what to buy next. Input: the customer's name.
    """
    if not customer_name or not customer_name.strip():
        customer_name = ""   # fall through to generic best-sellers below
    orders = session.query(Order).filter(
        Order.customer_name.ilike(f"%{customer_name}%")
    ).all() if customer_name else []
    if not orders:
        return ("Top picks this week:\n"
                "• Sony WH-1000XM5 Headphones — ₹29,990\n"
                "• Logitech MX Master 3 Mouse — ₹9,995\n"
                "• LG 27\" 4K Monitor — ₹34,990")
    purchased = [o.product for o in orders]
    recs = []
    if any("Laptop" in p for p in purchased):
        recs += ["• Laptop Stand (₹2,499) — Ergonomic posture upgrade",
                 "• USB-C 7-in-1 Hub (₹3,999) — Expand your ports"]
    if any("Mouse" in p or "Keyboard" in p for p in purchased):
        recs += ["• Ergonomic Mouse Pad with Wrist Rest (₹999)",
                 "• Mechanical Keyboard Wrist Rest (₹799)"]
    if any("Monitor" in p for p in purchased):
        recs += ["• Monitor Arm (₹4,499) — Reclaim your desk space",
                 "• Screen Cleaning Kit (₹299)"]
    if any("Webcam" in p or "Headphone" in p for p in purchased):
        recs += ["• USB Ring Light (₹1,299) — Perfect for video calls"]
    if not recs:
        recs = ["• Wireless Charging Pad (₹1,499)", "• Cable Management Kit (₹599)"]
    return ("Personalised picks for " + customer_name + ":\n\n"
            + "\n".join(recs[:4]))

"""---
## Part 3: Building Specialized Agents 🤖

### The concept of specialisation

In a hospital emergency room, you don't want the same doctor handling every case.
A broken bone goes to orthopaedics. A heart issue goes to cardiology.
Each specialist is brilliant at their domain and fast because they're focused.

Our system works the same way:
- **FAQ Agent** → brilliant at policy questions, never touches the database
- **Order Agent** → brilliant at tracking queries, never touches the FAQ
- **Recommendation Agent** → brilliant at personalised suggestions

Each agent has access to exactly one tool — the tool it needs for its job. Nothing more.

### `create_react_agent` — building an agent in one line

LangGraph ships a prebuilt called `create_react_agent`.

It automatically builds the full ReAct loop as a LangGraph graph:
- State definition ✅
- Agent node (LLM with tools) ✅
- Tools node (tool execution) ✅
- Conditional edge (loop until done) ✅
- Compile ✅

All from one function call.

"""


# ─── FAQ SPECIALIST ───────────────────────────────────────────────────────────
faq_agent = create_react_agent(
    model=llm,
    tools=[search_faq],
    prompt=(
        """You are ShopBot's FAQ Specialist — the go-to person for policies and procedures.
Expertise: returns, shipping times, payments, warranties, student discounts, EMI, GST.
ALWAYS call the search_faq tool before answering. Ensure the tool call arguments are perfectly valid JSON.
If the search results don't cover the question, OR the question is unrelated to our "
        "store (e.g. general trivia, coding, math), DO NOT make things up — politely say you can "
        "only help with orders, products, and store policies, and invite them to ask about those.
Be friendly, clear, and concise. End with: 'Anything else I can help with?'"""
    )
)


# ─── ORDER TRACKING SPECIALIST ────────────────────────────────────────────────
order_agent = create_react_agent(
    model=llm,
    tools=[lookup_order],
    prompt=(
        """You are ShopBot's Order Tracking Specialist — the calm voice when customers are anxious.
Job: check order status, delivery updates, shipping timelines.
Call lookup_order with the customer's name. If no name is available in the conversation, "
        "politely ask for the name the order was placed under instead of guessing.
If the request is unrelated to orders, gently steer them back to what you can help with.
Be empathetic — if an order is delayed, acknowledge the frustration first."""
    )
)

# ─── PERSONAL SHOPPING SPECIALIST ─────────────────────────────────────────────
rec_agent = create_react_agent(
    model=llm,
    tools=[recommend_products],
    prompt=(
        """You are ShopBot's Personal Shopping Specialist — a trusted friend who knows tech.
Job: recommend products that genuinely add value to the customer's setup.
Call recommend_products to get suggestions (it works with or without a name).
If the request is unrelated to shopping, gently steer them back to what you can help with.
Be enthusiastic but honest — only recommend what actually makes sense."""
    )
)

if __name__ == "__main__":
    # ─── Draw the internal graph of the FAQ Agent ────────────────────────────────
    print("Drawing the FAQ Agent's internal LangGraph structure...\n")

    try:
        display(Image(faq_agent.get_graph().draw_mermaid_png()))
    except Exception:
        print(faq_agent.get_graph().draw_mermaid())

    if "GROQ_API_KEY" in os.environ and os.environ["GROQ_API_KEY"] != "dummy_key_to_prevent_prompt":
        faq_agent.invoke({"messages": [HumanMessage("What is your return policy?")]})

        r = order_agent.invoke({"messages": [HumanMessage("Check orders for Bob Smith")]})
        print(r)

        r = rec_agent.invoke({"messages": [HumanMessage("Recommend products for Alice Johnson")]})
        print(r)

"""---
## Part 4: The Supervisor — Intelligent Routing 🧠

### The routing problem

We have three great specialists. But how does the system know which one to call for any given customer message?

The naive approach is keyword matching:
```python
if 'order' in message or 'track' in message:
    call order_agent
elif 'recommend' in message or 'suggest' in message:
    call rec_agent
else:
    call faq_agent
```

This looks clean. But consider these real customer messages:

| Customer says | Keyword match says | Correct route |
|---|---|---|
| "My Diwali gift hasn't shown up" | ❌ FAQ (no 'order') | ✅ Order Agent |
| "Something for my friend who loves coding" | ❌ FAQ (no 'suggest') | ✅ Rec Agent |
| "Is there EMI on the phone I'm looking at?" | ❌ Ambiguous | ✅ FAQ Agent |

Keyword matching fails whenever the customer expresses intent in unexpected words.

### The solution: let the LLM read and reason

Instead of keywords, we give the routing job to the LLM itself.

The LLM reads the full message, understands its intent, and returns a routing decision:
```python
{
  "agent": "order_agent",
  "reasoning": "Customer is asking about a missing delivery"
}
```

This works on *meaning*, not words. "Diwali gift hasn't shown up" → correctly routes to Order Agent.

### What is Structured Output?

There's one challenge: if we just ask the LLM "where should this go?", it might return:
*"I think this should go to the order tracking agent, because..."*

That's a string — we'd have to parse it, and parsing can fail.

**Structured output** solves this by forcing the LLM to return a specific Python object (via Pydantic):

```python
class RouteDecision(BaseModel):
    agent: Literal["faq_agent", "order_agent", "rec_agent"]  # ONLY these values
    reasoning: str                                             # explain why
```

With `llm.with_structured_output(RouteDecision)`, the LLM is guaranteed to return
a valid `RouteDecision` object — no string parsing, no errors.

"""

# ─── ROUTING SCHEMA ───────────────────────────────────────────────────────────
class RouteDecision(BaseModel):
    agent: Literal["faq_agent", "order_agent", "rec_agent"] = Field(
        description="The specialist agent that should handle this customer query"
    )
    reasoning: str = Field(
        description="One concise sentence explaining why this agent was chosen"
    )

# The router LLM: same model but constrained to return a RouteDecision
router_llm = llm.with_structured_output(RouteDecision)

# ─── SUPERVISOR STATE ─────────────────────────────────────────────────────────
# What information travels through the supervisor graph?
class SupervisorState(TypedDict):
    messages:   Annotated[list, add_messages]  # full conversation history
    next_agent: str                             # supervisor's routing decision

print("✅ Routing schema and supervisor state defined")
print()
print("SupervisorState carries:")
print("  messages   — the full conversation (grows with add_messages reducer)")
print("  next_agent — which specialist the supervisor chose to call")

# ─── ROUTING INSTRUCTIONS ─────────────────────────────────────────────────────
SUPERVISOR_INSTRUCTIONS = """You are ShopBot's Intelligent Supervisor.
Think of yourself as the sorting hub in Mumbai's Dabbawala network.
You do not answer customer questions — you route them to the right specialist.

Route to `faq_agent` for:
  - Return, refund, or exchange policies
  - Shipping times or delivery estimates
  - Payment options: UPI, EMI, net banking, credit cards
  - Warranty information, student discounts, GST invoices
  - How to contact customer support
  - General "how does X work?" questions

Route to `order_agent` for:
  - Status of a specific order
  - "Where is my package?" or concerns about late delivery
  - Dispatch confirmation or tracking number requests
  - Anything about a specific purchase a customer made

Route to `rec_agent` for:
  - Product recommendations or suggestions
  - Gift ideas or "what should I buy for..."
  - "Looking for something for..." queries
  - Accessories or products that pair with something they own

Read the INTENT, not just the keywords.
'My Diwali gift hasn't arrived' = order query (missing delivery).
'Something for my friend who loves photography' = recommendation query.
Be decisive. Pick exactly one agent."""

# ─── NODE FUNCTIONS ───────────────────────────────────────────────────────────
def supervisor_node(state: SupervisorState) -> dict:
    """The LLM reads the message and decides which specialist to call."""
    user_message = state["messages"][-1].content
    decision = router_llm.invoke([
        SystemMessage(content=SUPERVISOR_INSTRUCTIONS),
        HumanMessage(content=f"Route this customer query: '{user_message}'")
    ])
    print(f"  🧠 Routed to → {decision.agent}")
    print(f"  💭 Reasoning: {decision.reasoning}")
    return {"next_agent": decision.agent}


# recursion_limit caps each agent's internal ReAct loop so a tool-calling
# loop can never run away (it errors out quickly instead of hanging).
AGENT_CFG = {"recursion_limit": 8}

def run_faq_agent(state: SupervisorState) -> dict:
    result = faq_agent.invoke({"messages": state["messages"]}, config=AGENT_CFG)
    return {"messages": [result["messages"][-1]]}

def run_order_agent(state: SupervisorState) -> dict:
    result = order_agent.invoke({"messages": state["messages"]}, config=AGENT_CFG)
    return {"messages": [result["messages"][-1]]}

def run_rec_agent(state: SupervisorState) -> dict:
    result = rec_agent.invoke({"messages": state["messages"]}, config=AGENT_CFG)
    return {"messages": [result["messages"][-1]]}

def route_to_specialist(state: SupervisorState) -> str:
    """Conditional edge: reads state, returns the name of the next node."""
    return state["next_agent"]

print("✅ Supervisor and all specialist nodes defined")

# ─── BUILD THE MULTI-AGENT GRAPH (5 steps) ────────────────────────────────────

# Step 2: Builder
builder = StateGraph(SupervisorState)

# Step 3: Nodes
builder.add_node("supervisor",  supervisor_node)
builder.add_node("faq_agent",   run_faq_agent)
builder.add_node("order_agent", run_order_agent)
builder.add_node("rec_agent",   run_rec_agent)

# Step 4: Edges
builder.add_edge(START, "supervisor")                   # always start at supervisor

builder.add_conditional_edges(                          # supervisor routes conditionally
    "supervisor",
    route_to_specialist,                                # function that decides the route
    {
        "faq_agent":   "faq_agent",
        "order_agent": "order_agent",
        "rec_agent":   "rec_agent",
    }
)

builder.add_edge("faq_agent",   END)                    # each specialist leads to end
builder.add_edge("order_agent", END)
builder.add_edge("rec_agent",   END)

# Step 5: Compile
shopbot = builder.compile()

print("✅ Multi-agent graph compiled!")
print()
print("Flow: START → supervisor → [faq_agent | order_agent | rec_agent] → END")

# ─── Draw the full multi-agent system ────────────────────────────────────────
print("Drawing the complete multi-agent architecture...\n")

try:
    display(Image(shopbot.get_graph(xray=True).draw_mermaid_png()))
except Exception:
    print(shopbot.get_graph(xray=True).draw_mermaid())

# ─── Test the system ──────────────────────────────────────────────────────────

def ask(question: str):
    """Helper to test the multi-agent system with a single question."""
    print(f"\n{'─' * 65}")
    print(f"👤 Customer: {question}")
    print(f"{'─' * 65}")
    result = shopbot.invoke({
        "messages":   [HumanMessage(content=question)],
        "next_agent": ""
    })
    print(f"\n🤖 ShopBot: {result['messages'][-1].content}")

if __name__ == "__main__" and "GROQ_API_KEY" in os.environ and os.environ["GROQ_API_KEY"] != "dummy_key_to_prevent_prompt":
    ask("What is the return policy of Bob's last order?")

    # This message has no "order" keyword — the LLM must infer intent from context
    ask("My Diwali gift hasn't shown up yet — it was ordered for Alice Johnson")

    # This has no "recommend" or "suggest" keyword either
    ask("Looking for a nice gift for my friend who just bought a new laptop")

"""---
## Part 5: Memory — Making the System Remember 💾

### The problem: every message starts from zero

Try this thought experiment. Send these two messages one after the other:

**Message 1:** *"Hi! I'm Priya Patel. What's your return policy?"*
**Message 2:** *"Great. Can you also check my order status?"*

Right now, message 2 has no name in it.
The order agent receives `lookup_order("")` → finds nothing.

The system forgot who it was talking to.

### Why does this happen?

LangGraph graphs are **stateless by default**.

Each time you call `graph.invoke(...)`, the graph:
1. Starts with whatever state you pass in
2. Runs through all the nodes
3. Returns the final state
4. **Discards everything**

The next call starts completely fresh. There is no memory between invocations.

### The solution: Checkpointing with `MemorySaver`

LangGraph's **checkpointer** saves the entire state after every graph run,
tagged with a `thread_id` (conversation identifier).

```
thread_id = "priya-session-001"

Invoke 1 → graph runs → state saved for "priya-session-001"
Invoke 2 → graph LOADS state for "priya-session-001" first → then runs
```

Think of `thread_id` as the customer's conversation session.
Same thread_id = same conversation, continuous memory across messages.
Different thread_id = completely isolated, fresh start.

The analogy: this is the difference between a **new doctor** (asks your full history every visit)
and your **family doctor** (knows your history from day one, picks up exactly where you left off).

"""

# ─── Add memory to the graph ─────────────────────────────────────────────────

memory = MemorySaver()

# The graph is identical — the only change is at compile time
shopbot_with_memory = builder.compile(checkpointer=memory)

# The thread_id ties all three turns into one continuous conversation.
# NOTE: named priya_config (NOT `session`) so we don't clobber the SQLAlchemy
# DB `session` global that our tools depend on.
priya_config = {"configurable": {"thread_id": "priya-demo-001"}}
if __name__ == "__main__" and "GROQ_API_KEY" in os.environ and os.environ["GROQ_API_KEY"] != "dummy_key_to_prevent_prompt":
    # Turn 1: Priya introduces herself
    print("\n── Turn 1 ──────────────────────────────────────────────────────")
    print("👤 Priya: Hi! I'm Priya Patel. What's your return policy?")
    r = shopbot_with_memory.invoke(
        {"messages": [HumanMessage("Hi! I'm Priya Patel. What's your return policy?")], "next_agent": ""},
        config=priya_config
    )
    print(f"🤖 ShopBot: {r['messages'][-1].content[:300]}...")

    # Turn 2: No name given — bot must remember from Turn 1
    print("\n── Turn 2 — no name in this message ────────────────────────────")
    print("👤 Priya: Can you check my order status?")
    r = shopbot_with_memory.invoke(
        {"messages": [HumanMessage("Can you check my order status?")], "next_agent": ""},
        config=priya_config
    )
    print(f"🤖 ShopBot: {r['messages'][-1].content[:400]}...")

    # Turn 3: Still no name
    print("\n── Turn 3 — still no name ───────────────────────────────────────")
    print("👤 Priya: Recommend something for me!")
    r = shopbot_with_memory.invoke(
        {"messages": [HumanMessage("Recommend something for me!")], "next_agent": ""},
        config=priya_config
    )
    print(f"🤖 ShopBot: {r['messages'][-1].content[:400]}...")

    r = shopbot_with_memory.invoke(
        {"messages": [HumanMessage("Can you check my order status?")], "next_agent": ""},
        config=priya_config
    )

    print(r)

"""---
## Part 6: Observability — Inspect, Debug, and Replay 🔬

### What is Observability?

In software engineering, **observability** is the ability to understand what your system did,
why it did it, and how to reproduce or reverse it — without adding new print statements every time.

For an AI agent, this means being able to answer:
- What messages did the agent see at each step?
- Which tool did it call, and with what input?
- What did the tool return?
- At which point did the routing decision happen?

LangGraph gives you all of this through two mechanisms:

1. **`get_state()`** — read the current (or past) state of any conversation
2. **`get_state_history()`** — see every checkpoint ever saved for a thread

This is equivalent to `git log` for your AI agent's conversation memory.

"""

if __name__ == "__main__" and "GROQ_API_KEY" in os.environ and os.environ["GROQ_API_KEY"] != "dummy_key_to_prevent_prompt":
    snapshot = shopbot_with_memory.get_state(
        {"configurable": {"thread_id": "priya-demo-001"}}
    )

    print(snapshot)

    for i, msg in enumerate(snapshot.values["messages"]):
        kind    = type(msg).__name__
        preview = (msg.content or "[tool call / tool result]")[:90].replace("\n", " ")
        print(f"  [{i+1:02d}] {kind:<25} {preview}...")

AGENT_LABELS = {
    "faq_agent":   "\n\n_— FAQ Specialist_",
    "order_agent": "\n\n_— Order Tracking Specialist_",
    "rec_agent":   "\n\n_— Personal Shopping Specialist_",
}

def shopbot_respond(message: str, history: list, session_state: dict) -> str:
    # Each browser session gets its own thread_id on first message
    if "thread_id" not in session_state:
        session_state["thread_id"] = f"shopbot-{uuid.uuid4().hex[:8]}"

    config = {"configurable": {"thread_id": session_state["thread_id"]}}

    try:
        result = shopbot_with_memory.invoke(
            {"messages": [HumanMessage(content=message)], "next_agent": ""},
            config=config
        )
        response  = result["messages"][-1].content
        agent_tag = AGENT_LABELS.get(result.get("next_agent", ""), "")
        if not response or not response.strip():
            response = ("I'm not sure I can help with that one. I'm great with "
                        "**order status**, **product recommendations**, and **store "
                        "policies** (returns, shipping, payments, warranty). Ask me anything there!")
            agent_tag = ""
        return response + agent_tag
    except Exception:
        # Never show a raw traceback to a customer — degrade gracefully.
        return ("Sorry, I had a little trouble with that one 😅. "
                "I can help with **order status**, **product recommendations**, and "
                "**store policies** (returns, shipping, payments, warranty). "
                "Could you rephrase, or ask me about one of those?")


def main():
    """Main entry point to launch the ShopBot chatbot Gradio application."""
    with gr.Blocks(theme=gr.themes.Soft(), title="ShopBot — Multi-Agent AI") as demo:
        gr.Markdown("""
        # 🛍️ ShopBot — Powered by LangGraph
        *Multi-agent AI · LLM-powered routing · Persistent memory*

        **Try these to see the system in action:**
        - Introduce yourself by name, then ask about your orders in the next message
        - Ask about a delivery without using the word "order"
        - Ask for a gift recommendation without saying "recommend"
        """)

        session_state = gr.State({})
        chatbot = gr.Chatbot(
            height=460, label="ShopBot",
            type="messages",                 # Gradio 5 format: list of {role, content} dicts
            avatar_images=("👤", "🛍️"),
            show_copy_button=True,
        )

        with gr.Row():
            msg = gr.Textbox(
                placeholder="Ask me anything...",
                scale=5, label="", lines=1,
            )
            btn = gr.Button("Send 🚀", scale=1, variant="primary")

        gr.Examples(
            examples=[
                "What is your return policy?",
                "Hi! I'm Priya Patel. Can you check my orders?",
                "Recommend something for me",
                "My Diwali gift hasn't arrived — it was for Alice Johnson",
                "Do you offer zero-cost EMI?",
                "I'm looking for a gift for someone who loves photography",
            ],
            inputs=msg,
        )

        def respond(message, history, state):
            reply   = shopbot_respond(message, history, state)
            history = history + [
                {"role": "user",      "content": message},
                {"role": "assistant", "content": reply},
            ]
            return "", history, state

        btn.click(respond, [msg, chatbot, session_state], [msg, chatbot, session_state])
        msg.submit(respond, [msg, chatbot, session_state], [msg, chatbot, session_state])

    demo.launch(debug=True, share=True)


class ChatController:
    """
    ChatController manages the chatbot life cycle and starts the application
    by calling the main entry point function.
    """
    def __init__(self):
        pass

    def start(self):
        """Invoke the main entry point function of the chatbot application."""
        print("Starting ShopBot via ChatController...")
        main()


if __name__ == "__main__":
    controller = ChatController()
    controller.start()

